### ISSUE TITLE
Error: ENOENT: no such file or directory, open './dist/webpack/template.html'

### ISSUE THREAD

**Issue by hoovercj** [freeboardgame/FreeBoardGame.org#77]
I tried to clone this today and get it running but was unable to run `yarn run dev`. I was able to get it to run using `yarn run prod`, though. For context, I'm on Windows. Did I skip a step?

Repro steps:

* Clone repo
* CD into repo
* `yarn install`
* `yarn run dev`

**Output:**
```
$ webpack --progress --config dev.webpack.config.js; tsc; webpack --watch --progress --config dev.webpack.config.js | node dist/server.js
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, open './dist/webpack/template.html'
```

**Comment by jasonharrison** [comment]
Hi Cody,

Thanks for the report and I'm sorry you're having trouble. 

I think this relates to recent changes we made to make webpack reloads quicker. 

Could you try these steps In the root directory of the project?

* `tsc`
*  `yarn run dev` 

Let me know if this works.

Jason

**Comment by hoovercj** [comment]
I changed `dev` to have tsc as the first step and it does not help.

**Comment by jasonharrison** [comment]
Hmm.  I just cloned the repo in a new directory and tried to follow your steps to reproduce, but it worked fine for me.

* `git clone 
https://github.com/freeboardgame/FreeBoardGame.org.git`
* `cd FreeBoardGame.org`
*  `yarn install`
* `yarn run dev`

I am on Debian Linux and don't have a Windows machine readily available to test on.

@hoovercj Can you check whether dist/webpack/template.html exists?  If it does, I wonder if this has anything to do with Windows using backslashes for traversing directories (C:\blah\blah), because we use forward slashes in dev.webpack.config.js.

```javascript
      filename: path.resolve(__dirname, './dist/webpack/template.html'),
```

https://github.com/freeboardgame/FreeBoardGame.org/blob/master/dev.webpack.config.js#L47

**Comment by hoovercj** [comment]
I'll try changing the slashes later when I get a chance.

The file does not exist, though, I should have said that in the initial post. Should it? And if so, what should be creating it?

**Comment by flamecoals** [comment]
The file should exist and should be created by webpack. I have a windows machine handy and I will try to debug later today. Thanks for reporting :)
